import ContainerComponent from "./Container";
import CardComponent from "./Card";
import ColComponent from "./Col";
import FlexComponent from "./Flex";
import HeadingComponent from "./Heading";
import LinkButtonComponent from "./LinkButton";
import ParagraphComponent from "./Paragraph";
import DateComponent from "./Date";
import BoxComponent from "./Box";
import TitleComponent from "./Title";
import DescriptionComponent from "./Description";
import FormComponent from "./Form";
import BoxTitleComponent from "./BoxTitle";
import LinkTextComponent from "./LinkText";
import NavPostComponent from "./NavPost";
import GridComponent from "./Grid";
import ModalMenuComponent from "./ModalMenu";
import BoxRedesComponent from "./BoxRedes";
import ContextComponent from "./Context";

export const Container = (props) => <ContainerComponent {...props} />;
export const Card = (props) => <CardComponent {...props} />;
export const Col = (props) => <ColComponent {...props} />;
export const Flex = (props) => <FlexComponent {...props} />;
export const Heading = (props) => <HeadingComponent {...props} />;
export const LinkButton = (props) => <LinkButtonComponent {...props} />;
export const Paragraph = (props) => <ParagraphComponent {...props} />;
export const Date = (props) => <DateComponent {...props} />;
export const Box = (props) => <BoxComponent {...props} />;
export const Title = (props) => <TitleComponent {...props} />;
export const Description = (props) => <DescriptionComponent {...props} />;
export const Form = (props) => <FormComponent {...props} />;
export const BoxTitle = (props) => <BoxTitleComponent {...props} />;
export const LinkText = (props) => <LinkTextComponent {...props} />;
export const NavPost = (props) => <NavPostComponent {...props} />;
export const Grid = (props) => <GridComponent {...props} />;
export const ModalMenu = (props) => <ModalMenuComponent {...props} />;
export const BoxRedes = (props) => <BoxRedesComponent {...props} />;
export const Context = (props) => <ContextComponent {...props} />;
